### ISSUE TITLE
Unable to update profile image url

### ISSUE THREAD

**Issue by littlelearners** [gothinkster/django-realworld-example-app#1]
Hi, I'm new to Django. I tried to update profile image url field after completing the tutorial. However, it does not update.

When I change the api to https://conduit.productionready.io/api it works fine, it doesn't work when I use my own api. 

Hope someone could help me. Thank you in advance.

**Comment by jamesbrewerdev** [comment]
You'll need to share some code to get help. I don't see a repository on your profile.

**Comment by jamesbrewerdev** [comment]
I'm going to close this for now. Happy to re-open if you can provide some code.
