### ISSUE TITLE
Django Cors

### ISSUE THREAD

**Issue by hunterway55** [gothinkster/django-realworld-example-app#2]
Looks like a great project.

I tried installing in both python2.7 and python3.5 and got the same error.
When running 
```
python manage.py runserver
```
I got
```
mw_instance = middleware(handler)
TypeError: object() takes no parameters
```
So by upgrading to django=1.10.5 and adding django-cors-headers==1.3.1.

I was able to get the project to build.

Hopefully this helps someone

**Comment by priyadhoundiyal** [comment]
Thanks @hunterway55 ! I was able to build the project using this. :)
I've submitted a pull request with the change in requirements.txt referencing this issue

**Comment by jamesbrewerdev** [comment]
Closing as this is solved by @priyadhoundiyal's PR, which has been merged.
